#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

struct particle_state
{
    vec3 position;
    vec3 velocity;
};

layout(std140, binding=0) buffer State
{
    particle_state particles[256];
};

layout(local_size_x = 256) in;

void main()
{
    particles[gl_LocalInvocationIndex].position += particles[gl_LocalInvocationIndex].velocity * 0.01;
    particles[gl_LocalInvocationIndex].velocity.y -= 9.81*0.01;
}